#baseURL = 'http://raytang.cn/'
languageCode = 'en-us'
title = "Ray's log"
theme = 'hugo-theme-stack'

[permalinks.page]
post = '/blog/:year/:month/:day/:slug/'
page = ':slug'

[[params.widgets.page]]
type = "archives"

[params.widgets.page.params]
limit = 5

[[params.widgets.page]]
type = "tag-cloud"

[params.widgets.page.params]
limit = 10

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[params.footer]
since = 2015

[params.imageProcessing.content]
enabled = false

#[params.sidebar.avatar]
#enabled = false

[params.sidebar]
subtitle = "Full Stack Dev Ready for Immediate Hire"

[[menu.main]]
name = "Home"
url = "https://raytang.cn/"
identifier = "home"

[menu.main.params]
icon = "home"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/doubleright"

[menu.social.params]
icon = "brand-github"

[markup.highlight]
noClasses = false
#lineNos = true
#lineNumbersInTable = true
